twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        
fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - { name: "styles", items: [ 'Format', 'Font', 'Styles','Bold', 'Italic', 'Underline','TextColor' ] }