framework:
    workflows:
        formulaire_progression:
            type: 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\FormulaireProgression
            initial_marking: [attente_validation_collaborateur, attente_validation_manager]
            places:
                - attente_validation_collaborateur
                - premiere_validation_collaborateur
                - attente_validation_manager
                - premiere_validation_manager
                - fusionne
                - revision_manager
                - revision_collaborateur
                - validation_collaborateur
                - validation_manager
                - signature
 
            transitions:
                premiere_validation_collaborateur:
                    guard: "is_granted('ROLE_CONTRIBUTEUR')"
                    from: attente_validation_collaborateur
                    to: premiere_validation_collaborateur
                premiere_validation_manager:
                    guard: "is_granted('ROLE_MANAGER')"
                    from: attente_validation_manager
                    to: premiere_validation_manager
                a_fusionner:
                    guard: "is_granted('ROLE_MANAGER')"
                    from: [premiere_validation_collaborateur, premiere_validation_manager]
                    to:   fusionne
                revision_manager:
                    from: fusionne
                    to:   revision_manager
                revision_collaborateur:
                    from: revision_manager
                    to:   revision_collaborateur
                retour_revision_manager:
                    from: revision_collaborateur
                    to: revision_manager
                validation_collaborateur:
                    guard: "is_granted('ROLE_CONTRIBUTEUR')"
                    from: revision_collaborateur
                    to:   validation_collaborateur
                validation_manager:
                    guard: "is_granted('ROLE_MANAGER')"
                    from: validation_collaborateur
                    to: validation_manager
                signature:
                    guard: "is_granted('ROLE_MANAGER')"
                    from: validation_manager
                    to: signature