<?php

namespace ContainerU0gSF0o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ActivitesType' shared autowired service.
     *
     * @return \App\Form\ActivitesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ActivitesType.php';

        return $container->privates['App\\Form\\ActivitesType'] = new \App\Form\ActivitesType();
    }
}
