<?php

namespace ContainerXpIbQW2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7jeGz0xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7jeGz0x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7jeGz0x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'user' => ['privates', '.errored..service_locator.7jeGz0x.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.7jeGz0x": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'encoder' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
