<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU0gSF0o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU0gSF0o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU0gSF0o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU0gSF0o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU0gSF0o\App_KernelDevDebugContainer([
    'container.build_hash' => 'U0gSF0o',
    'container.build_id' => 'e30dbf45',
    'container.build_time' => 1629118209,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU0gSF0o');
