<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTboYPtr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTboYPtr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTboYPtr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTboYPtr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTboYPtr\App_KernelDevDebugContainer([
    'container.build_hash' => 'TboYPtr',
    'container.build_id' => '4e8b8f29',
    'container.build_time' => 1628597758,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTboYPtr');
